name: Deploy to pages.uoregon.edu/tgorordo

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pandoc Compile `index.html`
        uses: docker://pandoc/core:latest
        with:
          args: "--standalone --output=index.html README.md"
      - name: SFTP Upload `index.html` to `pages.uoregon.edu/tgorordo` in `~/public_html`
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: sftp.uoregon.edu
          username: tgorordo
          password: ${{secrets.pages_password}}
          local_path: ./index.html
          remote_path: ./public_html/index.html
